<template>
  <body>
    <!-- ***** Welcome Area Start ***** -->
    <div class="welcome-area q-px-md" id="welcome">
      <!-- ***** Header Text Start ***** -->
      <div class="header-text">
        <div class="container">
          <div class="row">
            <div
              class="left-text col-lg-6 col-md-12 col-sm-12 col-xs-12"
              data-scroll-reveal="enter left move 30px over 0.6s after 0.4s"
            >
              <h1>
                Data insights from <em class="text-primary">Roadtrips</em>
              </h1>
              <p>
                Get valueable data for your business from travelers around the
                world. Find out when your customers are traveling, where they
                are going, and how long they are staying.
              </p>
              <q-btn
                rounded
                size="lg"
                color="primary"
                @click="scrollToElement('TrialForm')"
                >Try now</q-btn
              >
            </div>
          </div>
        </div>
      </div>
      <!-- ***** Header Text End ***** -->
    </div>
    <!-- ***** Welcome Area End ***** -->

    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="about">
      <div class="container q-px-md">
        <div class="row q-gutter-md q-gutter-y-lg justify-around">
          <div class="col-lg-3 col-md-5 col-sm-8 col-xs-12">
            <q-card class="q-pa-md text-center" style="height: 430px">
              <h4 class="text-left full-width text-accent text-h2">01</h4>
              <div class="column justify-center">
                <div class="q-gutter-md">
                  <q-icon name="route" size="xl" />
                  <h2 class="text-h4">Travelling routes</h2>
                  <p>
                    See where your customers are coming from and where they are
                    going.
                  </p>
                  <!-- <q-btn label="Discover More" rounded color="primary" /> -->
                </div>
              </div>
            </q-card>
          </div>
          <div
            class="col-lg-3 col-md-5 col-sm-8 col-xs-12"
            data-scroll-reveal="enter bottom move 30px over 0.6s after 0.4s"
          >
            <q-card class="q-pa-md text-center" style="height: 430px">
              <h4 class="text-left full-width text-accent text-h2">02</h4>
              <div class="column justify-center">
                <div class="q-gutter-md">
                  <q-icon name="hotel" size="xl" />
                  <h2 class="text-h4">Overnight locations</h2>
                  <p>
                    Find out where your customers are staying and how long they
                    are staying. Get insights about the most popular
                    accomodation types.
                  </p>
                  <!-- <q-btn label="Discover More" rounded color="primary" /> -->
                </div>
              </div>
            </q-card>
          </div>
          <div
            class="col-lg-3 col-md-5 col-sm-8 col-xs-12"
            data-scroll-reveal="enter right move 30px over 0.6s after 0.4s"
          >
            <q-card class="q-pa-md text-center" style="height: 430px">
              <h4 class="text-left full-width text-accent text-h2">03</h4>
              <div class="column justify-center">
                <div class="q-gutter-md">
                  <q-icon name="schedule" size="xl" />
                  <h2 class="text-h4">Dwell time</h2>
                  <p>
                    Find out how long your customers are staying at a specific
                    region.
                  </p>
                  <!-- <q-btn label="Discover More" rounded color="primary" /> -->
                </div>
              </div>
            </q-card>
          </div>
        </div>
      </div>
    </section>
    <!-- ***** Features Big Item End ***** -->

    <div class="left-image-decor"></div>

    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="promotion">
      <div class="container q-px-md">
        <div class="row">
          <div
            class="right-text offset-lg-1 col-lg-6 col-md-12 col-sm-12 mobile-bottom-fix"
          >
            <ul>
              <li>
                <div class="row">
                  <div class="col-1 column justify-center">
                    <q-icon color="accent" name="cloud_download" size="xl" />
                  </div>

                  <div class="col-11">
                    <h4>1. Data Collection</h4>
                    <p>
                      Our travel insights are generated by thousands of users of
                      our Roadtrip planning tool. We help our users plan their
                      custom route and create their personal roadtrip. The data
                      is sent anonymously to Roaddata.
                    </p>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="col-1 column justify-center">
                    <q-icon color="accent" name="settings" size="xl" />
                  </div>

                  <div class="col-11">
                    <h4>2. Data Processing</h4>
                    <p>
                      The received data gets processed and prepared for
                      visualisation once a day for every trip. We analyse trends
                      and patterns in the roadtrip data and make it available
                      for you.
                    </p>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="col-1 column justify-center">
                    <q-icon color="accent" name="pie_chart" size="xl" />
                  </div>

                  <div class="col-11">
                    <h4>3. Data visualisation</h4>
                    <p>
                      The data is visualised in a dashboard that is easy to
                      understand and use. You can filter the travel insights by
                      date, region and other parameters.
                    </p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <!-- ***** Features Big Item End ***** -->

    <div class="right-image-decor"></div>

    <section class="q-px-md">
      <div class="heading q-my-xl">
        <h2 style="text-align: left">More about <em>Roadtrip Insights</em></h2>

        <p>
          We have been working on our roadtrip planning tool for over 4 years
          now. We helped thousands of travelers to plan their roadtrip, which
          generated more than 7000 worldwide and unique trips. <br />
          This generates a lot of valuable travel insights that can be used for
          your business. Now we want to help you to get this data in a visual
          appealing way.
        </p>
      </div>

      <q-img
        style="max-width: 800px"
        fit="cover"
        class="q-mb-xl"
        src="../landing-page-assets/images/roaddata-sample-dash.png"
      >
      </q-img>
    </section>

    <!-- ***** Testimonials Starts ***** -->
    <section class="section q-mt-xl" id="testimonials">
      <div class="container q-px-md">
        <div class="row">
          <div class="col-lg-8 offset-lg-2">
            <div class="center-heading">
              <h2>Start your trial now for <em>free</em></h2>
              <p>
                Our travel insights portal Roaddata is currently in development
                and will be available soon, but you can already register for a
                free trial.
              </p>
              <br />
              <p>
                If you register now with your email address, you can use our
                tool one month for free after its release. No hidden costs, no
                credit card required.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ***** Testimonials Ends ***** -->
  </body>
</template>

<style>
@import url('../landing-page-assets/css/landing-page.css');
</style>

<script lang="ts">
import { defineComponent } from 'vue';
import { scroll } from 'quasar';
const { getScrollTarget, setVerticalScrollPosition } = scroll;

export default defineComponent({
  name: 'LandingPage',
  methods: {
    scrollToElement(elId: string) {
      const el = document.getElementById(elId);

      if (!el) {
        return;
      }
      const target = getScrollTarget(el);
      const offset = el.offsetTop;
      const duration = 1000;
      setVerticalScrollPosition(target, offset, duration);
    },
  },
});
</script>
